# Key note: You do not define namespaces on storage classes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: agones-prom-store
provisioner: kubernetes.io/gce-pd # GCP-specific provisioner for Persistent Disks
parameters:
  type: pd-ssd # Defines the disk type (SSD)
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer # Ensures binding with the volume claim occurs on the correct node
reclaimPolicy: Delete # Deletes volume after cluster tear down.
allowVolumeExpansion: true # Allows increasing the size of the volume
